# Generated by Django 3.2.8 on 2021-10-15 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoid', models.TextField(max_length=300)),
                ('comment', models.TextField(max_length=300)),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(max_length=300)),
                ('name', models.TextField(max_length=300)),
                ('commentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.comment')),
            ],
        ),
    ]
